# Generated by Django 4.1.1 on 2022-09-16 12:01

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Изображение профиля')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Доступ администратора')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник организации')),
                ('role', models.CharField(default='Сотрудник', max_length=255, null=True, verbose_name='Права доступа')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
