# Generated by Django 4.1.1 on 2022-09-16 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpendableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Именование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('description', models.TextField(verbose_name='Описание')),
                ('arrive_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('image', models.ImageField(upload_to='images/materials/', verbose_name='Изображение')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('resp_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resp_user', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный пользователь')),
                ('temp_resp_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_temp_resp_user', to=settings.AUTH_USER_MODEL, verbose_name='Временно отвественный пользователь')),
            ],
            options={
                'verbose_name': 'Расходный материал',
                'verbose_name_plural': 'Расходный материал',
            },
        ),
        migrations.CreateModel(
            name='ExpendableMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Именование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
            ],
            options={
                'verbose_name': 'Тип расходного материала',
                'verbose_name_plural': 'Типы расходных материалов',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Именование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('slug', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Имя для фильтрации')),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expendable_materials.expendablematerialtype')),
            ],
            options={
                'verbose_name': 'Характеристика расходного материала',
                'verbose_name_plural': 'Характеристики расходных материалов',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendable_materials.expendablematerial', verbose_name='Расходный материал')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendable_materials.property', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики расходного материала',
                'verbose_name_plural': 'Значения характеристик расходных материалов',
                'ordering': ['material'],
            },
        ),
        migrations.AddField(
            model_name='expendablematerial',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expendable_materials.expendablematerialtype'),
        ),
        migrations.CreateModel(
            name='EquipmentExpendableMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='Оборудование')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expendable_materials.expendablematerial', verbose_name='Расходный материал')),
            ],
            options={
                'verbose_name': 'Расходный материала оборудования',
                'verbose_name_plural': 'Расходные материалы оборудования',
                'ordering': ['equipment'],
            },
        ),
    ]
